name: 'Flux branch and version'
description: 'Calculates version and branch information for building the Flux'
author: 'Teledyne FLIR ITS team'
inputs:
  version:
    required: true
    description: 'version'
    default: '9.9.9'
  default-ref:
    description: default branch/tag
  flux-server-ref:
    description: flux-server branch/tag/SHA
  flux-hybrid-ref:
    description: flux-hybrid branch/tag/SHA
  flux-web-ref:
    description: flux-web branch/tag/SHA
  flux-streaming-server-ref:
    description: flux-streaming-server branch/tag/SHA
  flux-proxy-ref:
    description: flux-proxy branch/tag/SHA
outputs:
  version-string:
    description: version string
  default-ref:
    description: default branch/tag
  flux-server-ref:
    description: flux-server branch/tag/SHA
  flux-hybrid-ref:
    description: flux-hybrid branch/tag/SHA
  flux-web-ref:
    description: flux-web branch/tag/SHA
  flux-streaming-server-ref:
    description: flux-streaming-server branch/tag/SHA
  flux-proxy-ref:
    description: flux-proxy-ref branch/tag/SHA
runs:
  using: 'node16'
  main: 'dist/index.js'
