name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  setup-action:
    runs-on: ubuntu-latest
    outputs:
      flux-server-ref: ${{ steps.branch-and-version.outputs.flux-server-ref }}
      flux-hybrid-ref: ${{ steps.branch-and-version.outputs.flux-hybrid-ref }}
      flux-web-ref: ${{ steps.branch-and-version.outputs.flux-web-ref }}
      flux-streaming-server-ref: ${{ steps.branch-and-version.outputs.flux-streaming-server-ref }}
    steps:
      - uses: actions/checkout@v4
      - id: branch-and-version
        uses: ./
        with:
          version: 4.0.1
          default-ref: task/reporting/TMSNG-1234
          overrides: server=task/reporting/TMSNG-1235;hybrid=task/reporting/TMSNG-1236;web=task/reporting/FLUXWEBAPP-123;
  test:
    runs-on: ubuntu-latest
    needs: [setup-action]
    steps:
      - run: | 
          # Parse refs from overrides
          if [[ "${{ needs.setup-action.outputs.flux-server-ref }}" != "task/reporting/TMSNG-1235" ]]; then
            echo "flux-server-ref is not correct:"
            echo "  expected: task/reporting/TMSNG-1235"
            echo "  actual: ${{ needs.setup-action.outputs.flux-server-ref }}"
            exit 1
          fi
          if [[ "${{ needs.setup-action.outputs.flux-hybrid-ref }}" != "task/reporting/TMSNG-1236" ]]; then
              echo "flux-hybrid-ref is not correct:"
              echo "  expected: task/reporting/TMSNG-1236"
              echo "  actual: ${{ needs.setup-action.outputs.flux-hybrid-ref }}"
              exit 1
          fi
          if [[ "${{ needs.setup-action.outputs.flux-web-ref }}" != "task/reporting/FLUXWEBAPP-123" ]]; then
              echo "flux-web-ref is not correct:"
              echo "  expected: task/reporting/FLUXWEBAPP-123"
              echo "  actual: ${{ needs.setup-action.outputs.flux-web-ref }}"
              exit 1
          fi
          # Fallback to default-ref
          if [[ "${{ needs.setup-action.outputs.flux-streaming-server-ref }}" != "task/reporting/TMSNG-1234" ]]; then
              echo "flux-streaming-server-ref is not correct:"
              echo "  expected: task/reporting/TMSNG-1234"
              echo "  actual: ${{ needs.setup-action.outputs.flux-streaming-server-ref }}"
              exit 1
          fi
          echo "All refs are correct!"
